'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
def newEvenFib(n):
    fib_list = [1,2]
    total = 2
    i = 2
    
    while True:
        current_value = fib_list[i-1] + fib_list[i-2]
        if n < 2:
            total = 0
            break 
        elif current_value < n:
            fib_list.append(current_value)

            if current_value % 2 ==0:
                total += current_value
        else:
            break
        
        i+=1
    
    print total 

newEvenFib(4000000)
