'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def testFib(n):
    test_list = [1, 2]
    total = 0
    for i in range(n):
        if i <= 1:
            continue
        else:
            test_list.append(test_list[i -1] + test_list[i -2])

    for num in test_list:
        if num % 2 == 0:
            total += num 
    print total 

testFib(10)

